# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20160301_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default=b'ywattar@gmail.com', max_length=254),
        ),
    ]
